# Generated by Django 4.1.7 on 2023-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
