# Generated by Django 4.1.7 on 2023-04-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_commentaire_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(),
        ),
    ]
